# Build settings
markdown:    kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md
encoding: utf-8

# Permalinks
permalink: pretty

# Setup
title:            "David Bradshaw"
tagline:          "Philosopher"
description:      "David Bradshaw is professor of Philosophy at the University of Kentucky and the author of <i>Aristotle - East and West</i>."
url:            https://keithbuhler.com/davidbradshaw
baseurl:        /

author:
  name:          
  url:            

# Gems

gems: [jekyll-paginate]

paginate: 5
 
# Custom vars


github:
  repo:           https://github.com/keithbuhler/davidbradshaw
