# Build settings
markdown:    kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md
encoding: utf-8

# Permalinks
permalink: pretty

# Setup
title:            "David Bradshaw"
tagline:          "Philosopher"
description:      "Professor of Philosophy at the University of Kentucky and author of <i>Aristotle - East and West</i>.</a>"

url:            "http://www.keithbuhler.com"
baseurl:        "/sample3/"

author:
  name:          
  url:            

# Gems

gems: [jekyll-paginate]

paginate: 5
 
# Custom vars


github:
  repo:           https://github.com/keithbuhler/sample3
