# Build settings
markdown:    kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md
encoding: utf-8

# Permalinks
permalink: pretty

# Setup
title:            "David Bradshaw"
tagline:          "Philosopher"
description:      "Professor of Philosophy at the University of Kentucky and author of <a href="https://www.amazon.com/Aristotle-East-West-Metaphysics-Christendom/dp/0521035562"><i>Aristotle - East and West</i>.</a>"

url:            https://keithbuhler.com
baseurl:        /davidbradshaw/

author:
  name:          
  url:            

# Gems

gems: [jekyll-paginate]

paginate: 5
 
# Custom vars


github:
  repo:           https://github.com/keithbuhler/davidbradshaw
