# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            David Bradshaw
tagline:          'Philosopher'
description:      'David Bradshaw is professor of Philosophy at the University of Kentucky and the author of <i>Aristotle: East and West</i>.
url:              http://keithbuhler.com
baseurl:          /davidbradshaw

author:
  name:           'Keith Buhler'
  url:            https://keithbuhler.com

paginate:         5

# Custom vars
version:          

github:
  repo:           https://github.com/keithbuhler/davidbradshaw
